/*
Copyright The cert-manager Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	metav1 "github.com/cert-manager/cert-manager/pkg/client/applyconfigurations/meta/v1"
)

// ACMEIssuerDNS01ProviderOVHApplyConfiguration represents a declarative configuration of the ACMEIssuerDNS01ProviderOVH type for use
// with apply.
//
// ACMEIssuerDNS01ProviderOVH is a structure containing the
// credentials configuration for The OVH API.
// see: https://support.us.ovhcloud.com/hc/en-us/articles/360018130839-First-Steps-with-the-OVHcloud-API
type ACMEIssuerDNS01ProviderOVHApplyConfiguration struct {
	// The name of the OVH endpoint to use.
	// This is typically set to 'ovh-eu'.
	Endpoint *string `json:"endpoint,omitempty"`
	// The OVH API Application key.
	ApplicationKey *string `json:"applicationKey,omitempty"`
	// The name and key of the secret containing the Application Secret.
	ApplicationSecret *metav1.SecretKeySelectorApplyConfiguration `json:"applicationSecretSecretRef,omitempty"`
	// The name and key of the secret containing the Consumer key.
	ConsumerKey *metav1.SecretKeySelectorApplyConfiguration `json:"consumerKeySecretRef,omitempty"`
}

// ACMEIssuerDNS01ProviderOVHApplyConfiguration constructs a declarative configuration of the ACMEIssuerDNS01ProviderOVH type for use with
// apply.
func ACMEIssuerDNS01ProviderOVH() *ACMEIssuerDNS01ProviderOVHApplyConfiguration {
	return &ACMEIssuerDNS01ProviderOVHApplyConfiguration{}
}

// WithEndpoint sets the Endpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Endpoint field is set to the value of the last call.
func (b *ACMEIssuerDNS01ProviderOVHApplyConfiguration) WithEndpoint(value string) *ACMEIssuerDNS01ProviderOVHApplyConfiguration {
	b.Endpoint = &value
	return b
}

// WithApplicationKey sets the ApplicationKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ApplicationKey field is set to the value of the last call.
func (b *ACMEIssuerDNS01ProviderOVHApplyConfiguration) WithApplicationKey(value string) *ACMEIssuerDNS01ProviderOVHApplyConfiguration {
	b.ApplicationKey = &value
	return b
}

// WithApplicationSecret sets the ApplicationSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ApplicationSecret field is set to the value of the last call.
func (b *ACMEIssuerDNS01ProviderOVHApplyConfiguration) WithApplicationSecret(value *metav1.SecretKeySelectorApplyConfiguration) *ACMEIssuerDNS01ProviderOVHApplyConfiguration {
	b.ApplicationSecret = value
	return b
}

// WithConsumerKey sets the ConsumerKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConsumerKey field is set to the value of the last call.
func (b *ACMEIssuerDNS01ProviderOVHApplyConfiguration) WithConsumerKey(value *metav1.SecretKeySelectorApplyConfiguration) *ACMEIssuerDNS01ProviderOVHApplyConfiguration {
	b.ConsumerKey = value
	return b
}
